services:
  - type: web
    name: alsa-trade-backend
    runtime: python3
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 8000
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: false