services:
  - type: web
    name: alsa-trade-backend
    runtime: python3
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 8000
    autoDeploy: false